### ISSUE TITLE
Your Button component should default to type="button"

### ISSUE THREAD

**Issue by anton-karlovskiy** [bpierre/addreth#8]
Long story short, whenever I click the copy button or the address, my forms are submitted unintentionally.
Re: https://mtsknn.fi/blog/button-type-button

@bpierre

**Comment by bpierre** [comment]
Thanks! :pray:  https://github.com/bpierre/addreth/releases/tag/v3.0.1

**Comment by anton-karlovskiy** [comment]
Thank you @bpierre for the quick fix.
